on:
  pull_request:
    branches: ["master"]
    paths:
    - ".github/workflows/opentracker-backend-ci.yaml"
    - "apps/opentracker/backend/**"

name: opentracker-backend CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --manifest-path apps/opentracker/backend/Cargo.toml

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --manifest-path apps/opentracker/backend/Cargo.toml --lib

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/postgres
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install SQLx CLI
        run: cargo install --debug sqlx-cli

      - name: Create database
        run: sqlx database create

      - name: Run migrations
        working-directory: ./apps/opentracker/backend
        run: sqlx migrate run

      - name: Run tests
        run: cargo test --manifest-path apps/opentracker/backend/Cargo.toml --test integration

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - run: cargo fmt --manifest-path apps/opentracker/backend/Cargo.toml --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --manifest-path apps/opentracker/backend/Cargo.toml -- -D warnings
