on:
  push:
    branches: ["master"]
    paths:
    - 'apps/foundation/**'
    - 'apps/tag-updater/**'
    - '.github/workflows/tag-updater-release.yaml'

name: tag-updater Release

env:
  APPLICATION_NAME: tag-updater

jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/tag-updater
    steps:
      - uses: actions/checkout@v5
      - name: Generate tag
        id: tag
        run: echo "::set-output name=value::$(date '+%Y%m%d-%H%M')"
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APPLICATION_NAME }}:${{ steps.tag.outputs.value }}
          context: ./apps
          file: ./apps/${{ env.APPLICATION_NAME }}/Dockerfile
      - name: Inform `tag-updater`
        run: |
          curl https://tags.opentracker.app/update -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.TAG_UPDATER_PASSPHRASE }}" --data '{"service": "${{ env.APPLICATION_NAME }}", "tag": "${{ steps.tag.outputs.value }}"}'
